column_name_mapping = {
    'Timestamp': 'timestamp',
    'Email Address': 'email',
    'First name': 'first_name',
    'Last name': 'last_name',
    'Phone number (please include country code)': 'phone_number',
    'Where are you currently located (city/town)?': 'location_city',
    'Where are you currently located (country)?': 'location_country',
    'Nationality': 'nationality',
    'Do you have the right to work where you live? (This information will be kept private)': 'right_to_work',
    'ID documents (This information will be kept private)': 'id_documents',
    'Do you have a bank account? (This information will be kept private.)': 'has_bank_account',
    "If you have a bank account, is it registered in the country where you currently live? (This information will be kept private.)": 'bank_account_registered_in_country',
    'Are you able to receive payments from abroad to your bank account? (This information will be kept private.)': 'receive_payments_abroad',
    'LinkedIn profile': 'linkedin_profile',
    'GitHub profile': 'github_profile',
    "Link to updated CV (please add a link to a Google doc, so as you update it, we do not need a new version)": 'cv_link',
    'Personal Website': 'personal_website',
    'Please check off all the skills that you have working knowledge in: [React]': 'skills_react',
    'Please check off all the skills that you have working knowledge in: [Python]': 'skills_python',
    'Please check off all the skills that you have working knowledge in: [CSS]': 'skills_css',
    'Please check off all the skills that you have working knowledge in: [Javascript]': 'skills_javascript',
    'Please check off all the skills that you have working knowledge in: [HTML]': 'skills_html',
    'Work preferences [Remote]': 'work_preference_remote',
    'Work preferences [Co-located]': 'work_preference_colocated',
    'Work preferences [Hybrid]': 'work_preference_hybrid',
    'How many years of work experience do you have? [Co-located (face to face)]': 'experience_years_colocated',
    'How many years of work experience do you have? [Remote]': 'experience_years_remote',
    'How many years of work experience do you have? [Hybrid]': 'experience_years_hybrid',
    'Do you have [Your own computer or regular access to a computer]': 'has_computer_access',
    'Do you have [Regular and reliable Internet access]': 'has_reliable_internet',
    'Do you have [A smart phone]': 'has_smartphone',
    'Do you have [Large amounts of unlimited mobile data]': 'has_unlimited_mobile_data',
    'Please add anything that you would like us to be able to share with potential employers.': 'additional_information_for_employers',
    'Please add anything that you would like us to know at Na\'amal in order to best support you in your job search.': 'additional_information_for_naamal'
}

column_data_types = {
    'timestamp': 'TIMESTAMP',
    'email': 'VARCHAR(255)',
    'first_name': 'VARCHAR(50)',
    'last_name': 'VARCHAR(50)',
    'phone_number': 'VARCHAR(20)',
    'location_city': 'VARCHAR(100)',
    'location_country': 'VARCHAR(100)',
    'nationality': 'VARCHAR(50)',
    'right_to_work': 'BOOLEAN',
    'id_documents': 'VARCHAR(255)',
    'has_bank_account': 'BOOLEAN',
    'bank_account_registered_in_country': 'BOOLEAN',
    'receive_payments_abroad': 'BOOLEAN',
    'linkedin_profile': 'VARCHAR(255)',
    'github_profile': 'VARCHAR(255)',
    'cv_link': 'VARCHAR(255)',
    'personal_website': 'VARCHAR(255)',
    'skills_react': 'BOOLEAN',
    'skills_python': 'BOOLEAN',
    'skills_css': 'BOOLEAN',
    'skills_javascript': 'BOOLEAN',
    'skills_html': 'BOOLEAN',
    'work_preference_remote': 'BOOLEAN',
    'work_preference_colocated': 'BOOLEAN',
    'work_preference_hybrid': 'BOOLEAN',
    'experience_years_colocated': 'INTEGER',
    'experience_years_remote': 'INTEGER',
    'experience_years_hybrid': 'INTEGER',
    'has_computer_access': 'BOOLEAN',
    'has_reliable_internet': 'BOOLEAN',
    'has_smartphone': 'BOOLEAN',
    'has_unlimited_mobile_data': 'BOOLEAN',
    'additional_information_for_employers': 'TEXT',
    'additional_information_for_naamal': 'TEXT'
}